# Generated by Django 4.2.16 on 2024-11-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_erp_system", "0002_user_groups_user_is_staff_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
