# Generated by Django 4.2.16 on 2024-11-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_erp_system", "0003_alter_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=150),
        ),
    ]
