# Generated by Django 4.2.16 on 2024-11-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_erp_system", "0006_option_delete_options_alter_ticket_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Options",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("baggage", "Baggage"),
                            ("meal", "Meal"),
                            ("service", "Service"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Option",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="options",
            field=models.ManyToManyField(blank=True, to="air_erp_system.options"),
        ),
    ]
