# Generated by Django 4.2.16 on 2024-11-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("air_erp_system", "0007_options_delete_option_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="model",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="seat",
            name="airplane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="air_erp_system.airplane",
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="seat_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="air_erp_system.seattype",
            ),
        ),
    ]
