# Generated by Django 4.2.16 on 2024-12-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_erp_system", "0008_alter_airplane_model_alter_seat_airplane_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="available_seats_count",
            field=models.IntegerField(default=0),
        ),
    ]
