# Generated by Django 4.2.16 on 2024-12-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("air_erp_system", "0009_flight_available_seats_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=30
                    ),
                ),
                ("passport_number", models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="passport_number",
        ),
        migrations.AddField(
            model_name="ticket",
            name="passenger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="air_erp_system.passenger",
            ),
        ),
    ]
