# Generated by Django 4.2.16 on 2024-12-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_erp_system", "0011_seattype_reserved_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
