# Generated by Django 4.2.16 on 2024-12-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("air_erp_system", "0012_passenger_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="flight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="air_erp_system.flight",
            ),
        ),
    ]
