# Generated by Django 4.2.16 on 2024-12-11 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("air_erp_system", "0013_seat_flight"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passengers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
