# Generated by Django 4.2.16 on 2024-12-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("air_erp_system", "0015_alter_flight_airplane"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="flight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flights",
                to="air_erp_system.flight",
            ),
        ),
    ]
