services:
  api:
    build:
      context: api
    image: air-erp-api:1.0
    container_name: air-erp-api
    command: >
      bash -c "python manage.py makemigrations --noinput
               python manage.py migrate --noinput &&
               gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=api_db
    depends_on:
      - api_db
  api_db:
    image: postgres:13
    container_name: air-erp-api-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: air-erp-api-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data: