export const API_ROUTES = {
  SIGN_IN: '/auth/sign-in/',
  SIGN_UP: '/auth/sign-up/',
  LOGOUT: '/auth/logout/',
  REFRESH: '/auth/refresh/',
  FLIGHT_SEARCH: '/flight/search/',
  FLIGHT_DETAILS: '/flight/details/',
  FLIGHT_DEPARTURES: '/flight/departures/',
  FLIGHT_DESTINATIONS: '/flight/destinations/',
  FLIGHT_DATES: '/flight/dates/',
  FLIGHT_BOOKING: '/flight/booking/',
  USER: '/user/',
  USER_FLIGHTS: '/user/flights/',
  USER_PASSENGERS: '/user/passengers/',
  PAYMENT_BOOKING_PAYMENT: '/payment/passengers/',
};
